POST http://localhost:3333/videos
//Formato dos dados enviados para o backEnd metas dados
Content-Type: application/json

{
    "title":"Teste DevTest",
    "description":"Testando o Envio em uma DB Nativa Local",
    "duration": 180
}


###
PUT https://nodedozero-jxmb.onrender.com/videos/a73c12ca-4cb6-4ad7-9e6a-edca195948fd
Content-Type: application/json

{
    "title": "Teste32",
    "description":"Testando o Envio em uma DB Nativa Local",
    "duration": 180
}

###
GET https://nodedozero-jxmb.onrender.com/videos

###
GET https://nodedozero-jxmb.onrender.com/videos?search=node
//Query Parameters

###
DELETE https://nodedozero-jxmb.onrender.com/videos/a73c12ca-4cb6-4ad7-9e6a-edca195948fd
